<a href="https://colab.research.google.com/github/fefo716/AnyoneAI/blob/main/Practice_Python_NumPy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Python

Recommendation: in addition to doing the exercises, we strongly suggest that you test and modify the code in this notebook. The best way to learn is by doing, 'breaking' the code and trying to understand why it stopped working. There is nothing irreversible, do not be afraid! You can always re-download the notebook.

## Variables

By creating a variable you are giving an object a name. Each variable must have a name through which we will refer to it, the names must be unique and, as far as possible, be as explicit as possible to avoid confusion.

Using the = assigns a value to a variable. It is not a mathematical/logical equal.

In [ ]:
x = 35
print(x)

y = 1.7
print(y)

z = x + y
print(z)

my_text = 'Hello!'
print(my_text)

35
1.7
36.7
Hello!


**TODO:** What is the difference in the following cell

In [ ]:
print(18.8)
print('18.8')

**TODO:** How do we remove a variable that we don't want to use anymore?

In [ ]:
# To complete

## Data Types

When we define a variable, depending on the content that we assign to it, it will be of a certain type. The most common data types of variables are: int, float, string and boolean.

**TODO:** What type are the following variables?

In [ ]:
a = 42
b = 7.8
c = True
t1 = 'hola'
t2 = '523'

In [ ]:
# To complete

**TODO:** Convert __a__ to float, __b__ to int and __c__ to string

In [ ]:
# To complete

## Operations

With the variables we define, we can perform different operations. Depending on the type of variable, there are different operations available.

In [ ]:
a = 20
b = 4
print(a+b)
print(a-b)

24
16


Operations can be performed even between different types of variables

In [ ]:
a = 20
b = 4.5

c = a+b
d = a-b

print(c)
print(d)

24.5
15.5


We can divide

In [ ]:
x = 10
y = 3
z = x / y
print(z)

3.3333333333333335


**TODO:** Calculate the percentage that represents the value 165 over a total of 648 and store it in a variable called percentage.

In [ ]:
# To complete

**TODO:** Calculate the sum and multiplication of the variables a, b and c. I.e. `a+b+c` and `a*b*c`.

In [ ]:
a = '12'
b = '-5.75'
c = '23.87'

In [ ]:
# To complete

## Lists

They are composed of a succession of objects in a certain order. They are defined by square brackets [], and the objects within them are separated by commas.

In [ ]:
my_list = [42, 10.7, True, 'Messi']
print(my_list)

[42, 10.7, True, 'Messi']


A very common question that one asks when working with lists is how many elements does it have.

In [ ]:
len(my_list)

4

Each element in a list is assigned a position (index) that we can use to inspect or operate on that element. Indices start at 0, and are specified by putting square brackets with the index inside after the list name:

In [ ]:
my_list = [5, 6.0, 'Messi',-5, False, 'Maradona', True, 100]

print(my_list[0])
print(my_list[1])
print(my_list[2])

5
6.0
Messi


**TODO:** print the seventh element of my_list.

In [ ]:
# To complete

We can also, slice a list.

In [ ]:
print(my_list[0:3])
print(my_list[4:])
print(my_list[1:5:2])

[5, 6.0, 'Messi']
[False, 'Maradona', True, 100]
[6.0, -5]


What is the logic that governs this syntax? Play around with it a bit and see if you can figure out the rule. If not, you can also google what slicing is.

We can also use negative numbers for indexing.

In [ ]:
print(my_list[-1])
print(my_list[-2])
print(my_list[-8])

100
True
5


We can have list of lists.

In [ ]:
my_list_1 = ['hello', 'how', 'are', 'you?'] 
my_list_2 = [1, 2, 3]
mother_list = [0, my_list_1, 'Mas texto', my_list_2]

print(mother_list)
print(len(mother_list))

[0, ['hello', 'how', 'are', 'you?'], 'Mas texto', [1, 2, 3]]
4


**TODO:** Taking my_list_1 from mother_list (what we just did in the previous cell), index the second element of my_list_1.

In [ ]:
# To complete

Append values to a list

In [ ]:
empty_list = []
len(empty_list)

0

In [ ]:
empty_list.append(89)
empty_list.append('text')
print(empty_list)
print(len(empty_list))

[89, 'text']
2


**TODO:** What happens if they run the previous cell again and again?

**TODO:** Define a list and append a, b and c

In [ ]:
a = 8
b = 'world'
c = [12,24.5,66]

In [ ]:
# To complete

We must be careful when we copy lists and operate on it, let's see a little about what it is

In [ ]:
list_1 = [1, 2, 3, 4]
list_2 = list_1
list_2[-1] = 100

print(list_1, list_2)

[1, 2, 3, 100] [1, 2, 3, 100]


Note that both lists have been modified! This, in general, is not what is desired. But we can do it right:

In [ ]:
list_1 = [1, 2, 3, 4]
list_2 = list_1.copy()
list_2[-1] = 100
    
print(list_1, list_2)

[1, 2, 3, 4] [1, 2, 3, 100]


## Dictionaries

Dictionaries in Python are a type of data structure that allows you to store an unordered set of key:value pairs, the keys being unique within the same dictionary (that is, there cannot be two elements with the same key).

Let's see below an example of how we would declare a dictionary in Python in whose elements we have the Boca Juniors players of the year 2000, the key being the number of their shirt (unique key) and the value being their name:

In [ ]:
players = dict()
players = {
    1 : "Córdoba", 4 : "Ibarra",
    2 : "Bermúdez", 13 : "Traverso",
    6 : "Matellán", 22 : "Battaglia",
    5 : "Serna", 18 : "Basualdo",
    10 : "Riquelme", 9 : "Palermo",
    16 : "Delgado"
}
players

{1: 'Córdoba',
 4: 'Ibarra',
 2: 'Bermúdez',
 13: 'Traverso',
 6: 'Matellán',
 22: 'Battaglia',
 5: 'Serna',
 18: 'Basualdo',
 10: 'Riquelme',
 9: 'Palermo',
 16: 'Delgado'}

As we can see, the dictionary is declared between the characters {} and each of the elements is separated by commas (,). We define each element with its key:value pair, which can be the key and the value of any data type ('int', 'float', 'chr', 'str', 'bool', 'object').

Next we are going to loop through the dictionary and print its key:value pairs (we will see all the dictionary methods later):

In [ ]:
for k, v in players.items():
    print("%s -> %s"%(k,v))

1 -> Córdoba
4 -> Ibarra
2 -> Bermúdez
13 -> Traverso
6 -> Matellán
22 -> Battaglia
5 -> Serna
18 -> Basualdo
10 -> Riquelme
9 -> Palermo
16 -> Delgado


**TODO:** Print dictionary keys

In [ ]:
# To complete

**TODO:** Print dictionary values

In [ ]:
# To complete

**TODO:** Insert a new player into the dictionary, 7: 'Schelotto'

In [ ]:
# To complete

**TODO:** Investigate the setdefault method

In [ ]:
# To complete

**TODO:** Delete the element whose key is 22

In [ ]:
# To complete

**TODO:** Copy the dictionary to a new dictionary

In [ ]:
# To complete

**TODO:** Deletes all previously copied dictionary content

In [ ]:
# To complete

**TODO:** Check that keys 2 and 8 exist in the players dictionary

In [ ]:
# To complete

Another very useful method; is the items() method that returns the elements of the dictionaries in tuples, in which in each of them the key is in the first position and the value in the second.

**TODO**: Using items() iterate over the dictionary and print each key:value pair from the dictionary

In [ ]:
# To complete

Finally we are going to see the update(dict) method that will allow us to join the elements of two dictionaries. This method inserts into the dictionary those elements of the dictionary passed to it as a parameter, whose keys are not in the dictionary.

**TODO:**
Create a dictionary with substitute players (no matter the names or numbers, you can invent them) and add those players to the original dictionary.

In [ ]:
# To complete

## Sets

A set is created by placing all the items (elements) inside curly braces {}, separated by comma, or by using the built-in set() function.

It can have any number of items and they may be of different types (integer, float, tuple, string etc.). But a set cannot have mutable elements like lists, sets or dictionaries as its elements.

In [ ]:
A = {'python', 'pandas', 'numpy', 'matplotlib', 'csv', 'reports', 'sql', 'cloud'} # tools/skills for DS/ML
B = {'python', 'cloud', 'java', 'ruby', 'sql', 'jacascript'} # tools/skills for Backend

If we want to obtain the union of both sets of skills we can generate the union of the sets

In [ ]:
A.union(B)

{'cloud',
 'csv',
 'jacascript',
 'java',
 'matplotlib',
 'numpy',
 'pandas',
 'python',
 'reports',
 'ruby',
 'sql'}

**TODO:** What are the skills shared by both jobs?

In [ ]:
# To complete

**TODO:** What skills correspond to a DS position but not to a Backend position?

In [ ]:
# To complete

**TODO:** What skills correspond to a Backend position but not to a DS position?

In [ ]:
# To complete

## Loops

In general, when we are programming, we want to repeat an operation several times. For example, applying an operation to the elements of a list. If the list has many elements, it can be cumbersome to write the application of that operation to each element one by one, so we need some code structure that facilitates that syntax.

Loops are fundamental code structures in any programming language. They consist of blocks of code that are repeated a certain number of times given a condition. There are two basic ways to create loops, for statements and while statements.

### For

In [ ]:
list_numbers = [3, 55, 1, 876, 12]

for n in list_numbers:
    print(n)

3
55
1
876
12


Pay particular attention that the code "inside" the for is indented. In some programming languages, indentation is used to order the code, making it more readable. In Python, however, it is required. It is achieved with four spaces or a tab.

In [ ]:
list_numbers = [3, 55, 1, 876, 12]
i = 0

for n in list_numbers:    
    i = i + 1
    print(n, i)

3 1
55 2
1 3
876 4
12 5


In [ ]:
list_names = ['Martin', 'Juan', 'Ana']
new_list = []

for item in list_names:
    sentence = 'My name is ' + item
    new_list.append(sentence)

print(new_list)

['My name is Martin', 'My name is Juan', 'My name is Ana']


**TODO:**

If we have a list of numbers, for example the first ten natural numbers, and we try to add a fixed number to the list, for example 5, we may try something similar to the following:

In [ ]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(numbers + 3)

TypeError: ignored

We get an error! (Note that the option to Google the error on Stack Overflow this time is more informative).
So, we suggest you solve the following exercises:

* Create a routine that adds three to the first ten natural numbers and prints on the screen as it does so.
* Create a routine that adds three to the first ten natural numbers and saves the results in a new list. At the end, print that list on screen.

In [ ]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
for number in numbers:
    print(number + 3)

3
4
5
6
7
8
9
10
11
12


In [ ]:
numbers = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
results = []
for number in numbers:
    results.append(number + 3)
print(results)

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


**TODO:** Repeat the same but now for the first 100 natural numbers. Don't manually write the full list, use `range`.

In [ ]:
# To complete

**TODO:** Generate a list called my_list that contains the square of each element in the numbers list

In [ ]:
numbers = [3, 1, 5, 7, 12, 10, 17, 4, 22]

In [ ]:
# To complete

**TODO:** Add all the elements of the following list

In [ ]:
numbers = [4, 8, 3, 1, -3, 3, -5, 1, 2, -8]

In [ ]:
# To complete

**TODO:** Print the table from 1 to 9

In [ ]:
for i in range(1,11):
  print("\n")
  print(f'Esta es la tabla del {i}')
  for b in range(0,10):
    m = (i*b)
    print(f'{i} X {b} = {m}')
    







Esta es la tabla del 1
1 X 0 = 0
1 X 1 = 1
1 X 2 = 2
1 X 3 = 3
1 X 4 = 4
1 X 5 = 5
1 X 6 = 6
1 X 7 = 7
1 X 8 = 8
1 X 9 = 9


Esta es la tabla del 2
2 X 0 = 0
2 X 1 = 2
2 X 2 = 4
2 X 3 = 6
2 X 4 = 8
2 X 5 = 10
2 X 6 = 12
2 X 7 = 14
2 X 8 = 16
2 X 9 = 18


Esta es la tabla del 3
3 X 0 = 0
3 X 1 = 3
3 X 2 = 6
3 X 3 = 9
3 X 4 = 12
3 X 5 = 15
3 X 6 = 18
3 X 7 = 21
3 X 8 = 24
3 X 9 = 27


Esta es la tabla del 4
4 X 0 = 0
4 X 1 = 4
4 X 2 = 8
4 X 3 = 12
4 X 4 = 16
4 X 5 = 20
4 X 6 = 24
4 X 7 = 28
4 X 8 = 32
4 X 9 = 36


Esta es la tabla del 5
5 X 0 = 0
5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45


Esta es la tabla del 6
6 X 0 = 0
6 X 1 = 6
6 X 2 = 12
6 X 3 = 18
6 X 4 = 24
6 X 5 = 30
6 X 6 = 36
6 X 7 = 42
6 X 8 = 48
6 X 9 = 54


Esta es la tabla del 7
7 X 0 = 0
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63


Esta es la tabla del 8
8 X 0 = 0
8 X 1 = 8
8 X 2 = 16
8 X 3 = 24
8 X 4 = 32
8 X 5

### While

Python While Loop is used to execute a block of statements repeatedly until a given condition is satisfied.

In [ ]:
count = 0
while count < 7:
    count = count + 1
    print(count)

1
2
3
4
5
6
7


**TODO:** Using python's input() function, create a loop that prints the characters the user enters, until the char __z__ is detected.

In [ ]:
while True:
  b = input("Ingresa tu nombre: ")
  for a in b:
    if a != "z":
      print(a)
      else:
        pass
    elif a == 'z':
      print('I have a Z')
      break
    else:
      pass




Ingresa tu nombre: fede
f
e
d
e


KeyboardInterrupt: ignored

**TODO:** Using an input build a program that allows a user to enter only positive numbers and add them up. When the user sends the number 0, the program ends and shows the total sum of the numbers entered.

In [ ]:
a = 0
while True:
  
  # b no puede ser negativo
  # b == CERO se corta el programa, debe sumar todos los inputs
  # si b es positivo: almacenar suma y volver a preguntar otro nro.
  
  b = int(input('Ingrese un nro: '))
  if b < 0:
    print('usted ingresó un nro negativo, por favor, ponga un nro positivo')
  elif b > 0:
    a += b
  elif b == 0:
    print(f'Final del juego, el acumulado es {a}')
    break
  else:
    print('sabes lo que son los numeros?')


Ingrese un nro: 0
Final del juego, el acumulado es 0


#### History of chess

When the creator of the game of chess showed his invention to the king of a far Eastern country, the latter was so pleased that he gave the inventor the right to decide for himself what his reward would be for such a creation. The man, who was very wise, asked the king something that at first appeared to be quite humble: that for the first square on the chessboard, he should receive one grain of wheat, two for the second, four for the third, and so on, doubling the amount each time.

**TODO:** The chessboard has 64 squares, using a while show how many grains of wheat the creator would charge for each square that the board has

In [ ]:
'''a = 1
while True:
  # recorrer del 1 al 64, 
  # duplicar el anterior resultado
  # mostrar el resultado por cada posición del tablero (1 al 64)

  print(f'Para la posición 1, el jugador carga 1 grano de trigo')
  b = 0
  for i in range(2,65):
    a = a*2
    print(f'Para la posicion {i}, el jugador carga {a} granos de trigo')

  break'''

'''square = 0
while square < 65:
  
  for n in range(1,65):
        square  += 1
        square_num = (2**(square-1))               
        print(f"Square_{n}: {square_num:,}")
        
  break'''

# tade
square = 0
total = 0

while square < 65:
    print(2**square)
    square = square + 1



1
2
4
8
16
32
64
128
256
512
1024
2048
4096
8192
16384
32768
65536
131072
262144
524288
1048576
2097152
4194304
8388608
16777216
33554432
67108864
134217728
268435456
536870912
1073741824
2147483648
4294967296
8589934592
17179869184
34359738368
68719476736
137438953472
274877906944
549755813888
1099511627776
2199023255552
4398046511104
8796093022208
17592186044416
35184372088832
70368744177664
140737488355328
281474976710656
562949953421312
1125899906842624
2251799813685248
4503599627370496
9007199254740992
18014398509481984
36028797018963968
72057594037927936
144115188075855872
288230376151711744
576460752303423488
1152921504606846976
2305843009213693952
4611686018427387904
9223372036854775808


## if/elif/else

**TODO:** Using if, elif and else validate check if the variable `number` is positive, negative or equal to 0.

In [ ]:
# You can change this variable to check different numbers
number = -1

# To complete

**TODO:** Through an if compare the two variables (`age_1`, `age_2`) and show the highest value


In [ ]:
age_1 = 10
age_2 = 20

# To complete

**TODO:** Validate through an if if the value stored in the `even_validation` variable is even or odd

In [ ]:
even_validation = 19

if even_validation % 2 == 0:
  print('the number is even')
else:
  print('it´s odd')

In [ ]:
a = 10
print(type(a))

<class 'int'>


In [ ]:
b = a / 2
print(type(b))

<class 'float'>


**TODO:** Compare the 3 variables (a, b, c) so that it returns which is the largest value. In case all 3 values are equal, return the message 'All values are equal'.

Make different tests to show that A is greater, that B is greater, that C is greater and that the 3 are equal.

In [ ]:
# To complete

**TODO:** Validate what type of data the variable is, returning the message 'It's a number' or 'It's a string' depending on the case. Swap values from string to numeric in the data_type variable to test if it works correctly.

In [ ]:
# To complete
input_var = 100.0

# code



**TODO:** Let's go with something a little more complicated.

* Check if the variable number is a multiple of 2
* If it is a multiple of 2, check if it is a multiple of 4.
* If it is a multiple of 2, validate if it is a multiple of 6
* And if it is a multiple of 4, validate if it is a multiple of 6

In [ ]:
# To complete

**TODO:** Investigate how to do a REDUCED IF (or inline if).

Once that is done, create a greeting variable that is equal to a reduced if that validates the language variable and shows by message 'HELLO' if the language is Spanish or 'HI' if the language is English

In [ ]:
# To complete

**TODO:** Investigate how to know if a value is inside a list

Using the vowel list check with an IF if the value of the letter variable is inside the list. If this show by message 'It's a vowel'. If it is not show by message 'It is not a vowel'

In [ ]:
vowel = ['a','e','i','o','u','á','é','í','ó','ú']
letter = 'o'

In [ ]:
# To complete

## Functions

**TODO:** Create 4 functions and each one receives parameter 2 values
* my_sum
* my_subtraction
* my_division
* my_multiplication

To each function add a description so that it can be seen when using help(). Explain in the description how to use the function and which values it accepts and which it does not. Validate in the function that the values received are integers, otherwise return a message saying "Verify the data entered, both have to be integers".

Addition, subtraction and multiplication will be similar, but division has something different, validate that the dividend is not 0 or otherwise display the message "The divisor cannot be zero".

In [ ]:
# To complete

In [ ]:
my_sum(13, 45)
my_subtraction(1000, 545)
my_division(200, 10)
my_multiplication(10, 4343)

---

# 2. NumPy

It is very important that you google and consult the documentation. If you didn't install it, now is a good time. When we want to use a library, we must first import it.

Now our work environment knows that if we put something like __np.__ it means that this functionality must be found in NumPy. Important: If the library was NOT installed correctly, you will get an error message.

The main data type that NumPy works on are arrays. Arrays are similar to lists and can actually be created from them.

In [ ]:
import numpy as np

In [ ]:
my_list = [0,1,2,3,4,5]
array = np.array(my_list)

print(my_list)
print(array)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


But they are more than a list. Some things that couldn't be done with lists can now be done with fixes. Remember that adding a number to the entire list was not allowed.

In [ ]:
my_list + 1

TypeError: can only concatenate list (not "int") to list

But now with the arrays yes!

In [ ]:
array + 1

array([1, 2, 3, 4, 5, 6])

In [ ]:
print(array - 5)
print(array - 2)
print(array * 4)
print(array ** 2)

[-5 -4 -3 -2 -1  0]
[-2 -1  0  1  2  3]
[ 0  4  8 12 16 20]
[ 0  1  4  9 16 25]


**TODO:** Except for multiplication, none was allowed in lists. What does multiplication do for a list?

## Array Creation

While we can create arrays from lists, NumPy comes with many features to do so. Let's see some.

A widely used one is __np.arange()__. Check your documentation. Alternatively, in a code cell, type __np.arange__ and press __shift + tab__. That way, help will appear.

Play around with the example below.

In [ ]:
array = np.arange(3, 20, 2)
print(array)

[ 3  5  7  9 11 13 15 17 19]


**TODO:**
Investigate and create examples with the following functions

* np.linspace
* np.arange
* np.zeros and np.ones

## Array Shape
Arrays have many more properties than lists. In particular, they may have more than one axis or dimension. Let's see what we mean:

In [ ]:
array_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(array_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
array_2d.shape

(2, 4)

In [ ]:
array_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(array_2d)
print(array_2d.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


If we want to know how many elements it has, we can use __.size__

In [ ]:
print(array_2d.size)

8


## Arrays operations

NumPy arrays come with a bunch of functions that operate on arrays.

In [ ]:
array = np.array([-100,2,3,17,25,1,95])

print(array.min())
print(array.max())

-100
95


In the 2D case, we can request that these functions operate on the entire array, or by axes.

**TODO:** Try to understand the difference between the following instructions

In [ ]:
print(array_2d.max())
print(array_2d.max(axis=0))
print(array_2d.max(axis=1))

## Slicing

We didn't say anything about indexing or slicing. This is because, for 1D arrays, it is similar to that for lists. For 2D arrays, it's slightly more complicated.

In [ ]:
array_2d = np.arange(9).reshape(3,3)

print(array_2d)
print(array_2d[1,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]


**TODO:** Write an array with 100 equally spaced numbers from 0 to 9

In [ ]:
# To complete

**TODO:** Create a 1D array of 20 zeros. Replace the first 15 elements with ones.

In [ ]:
# To complete

**TODO:** Create a 1D array of 50 zeros. Replace the first 25 elements with the natural numbers from 0 to 24.

In [ ]:
# To complete

**TODO:** Create a 2D array of 3 rows and 3 columns, filled with zeros. Replace the elements of the second column by the numbers 1, 2 and 3 respectively.

In [ ]:
# To complete

**TODO:** Create a 2D array of 3 rows and 3 columns, filled with zeros. Replace the elements of the diagonal by ones.

In [ ]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# To complete
import numpy as np

arr = np.zeros((3,3))
diag = np.diag([1]*3)
w = np.where(diag == 1)
arr[w] = 1

arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
w = np.where(diag == 1)
arr = np.zeros((3,3))
arr[w] = 1
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.where(diag == 1)

(array([0, 1, 2]), array([0, 1, 2]))

In [ ]:
np.sort
np.argsort


<function numpy.argwhere>

**TODO:** Create a 2D array of 100 rows and 100 columns, filled with zeros. Replace the elements of the diagonal by ones.

In [ ]:
# To complete

## Statistics

Descriptive Statistics helps us to begin to analyze and understand a set of data. In the case of numerical data, it does so by obtaining statistical values that, in some way, replace our data. For example, it is very difficult to read and understand the age of 1000 people. But with a reduced set of statistical values (minimum, maximum, mean and standard deviation, etc.) we can approximate that set in a much more understandable way.

Given a set of numbers, the average is usually considered the most representative number of that set. This is not always the case.

**TODO:**
Given the following list of numbers, write a routine that computes their mean, [variance](https://en.wikipedia.org/wiki/Variance), and [standard deviation](https://en.wikipedia.org/wiki/Standard_deviation).

In [ ]:
my_list = [11, 12, 63, 31, 82, 56, 32, 686, 1, 2, 39, 9, 99, 2, 1]
n = len(my_list)

In [ ]:
# To complete

**TODO:** Now with NumPy

In [ ]:
# To complete

## Random

One extremely useful thing we can do with NumPy is to generate random samples. These functions are found within the NumPy random package.

In [ ]:
die_samples = np.random.randint(1, 7, size=15)
print(die_samples)

die_samples = np.random.choice([1, 2, 3, 4, 5, 6], size=15)
print(die_samples)

[3 1 1 6 1 4 5 2 3 3 4 1 6 6 2]
[2 3 2 2 3 5 5 3 4 1 2 6 2 6 4]


**TODO:**
What will be the mean of the values obtained by throwing a die many times? We are going to try to answer this question by simulating a die. For it:

* Get random samples of a die with differet sample size (e.g. 10, 100, 1000, ...).
* Calculate its mean and standard deviation.
* From what number of samples does the average "stabilize"?

In [ ]:
# To complete

**TODO:**

Simulate a loaded die to favor a value of your choice. For example, the 6. To do this, consult the help of the __np.random.choice__ function. How do you modify the mean and standard deviation?

In [ ]:
# To complete

---

# 3. Pandas

Pandas is the best known Python library for manipulating and analyzing data. It is built on top of NumPy, so many features are similar. We will use Pandas to work with structured datasets.

Just as NumPy provides us with arrays and with them we access many new features, Pandas provides us with DataFrames and Series. By far the most used object is the first one, DataFrames.

We are going to use the open data of the Argentine government, so you will have to download the csv from the following link: [Names 2010-2014](https://www.datos.gob.ar/dataset/otros-nombres-personas-fisicas)

In [1]:
import pandas as pd
import numpy as np

## Reading a csv file

In [17]:
df_names = pd.read_csv('nombres-2010-2014.csv')
df_names

nombre  cantidad  anio
0                     Benjamin      2986  2010
1                        Sofia      2252  2010
2                     Bautista      2176  2010
3                      Joaquín      2111  2010
4                 Juan Ignacio      2039  2010
...                        ...       ...   ...
871489            Leire Jasmin         1  2014
871490  Isaias Sebastian Ariel         1  2014
871491        Yanira Valentina         1  2014
871492            Angie Ainara         1  2014
871493          Elias Hernando         1  2014

[871494 rows x 3 columns]

## Columns renaming

First of all let's rename the columns to name, amount and year

In [20]:
df_names = df_names.rename(columns={'nombre': 'name', 'cantidad': 'amount', 'anio': 'year'})
df_names

name  amount  year
0                     Benjamin    2986  2010
1                        Sofia    2252  2010
2                     Bautista    2176  2010
3                      Joaquín    2111  2010
4                 Juan Ignacio    2039  2010
...                        ...     ...   ...
871489            Leire Jasmin       1  2014
871490  Isaias Sebastian Ariel       1  2014
871491        Yanira Valentina       1  2014
871492            Angie Ainara       1  2014
871493          Elias Hernando       1  2014

[871494 rows x 3 columns]

In [21]:
df_names.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 871494 entries, 0 to 871493
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   name    871494 non-null  object
 1   amount  871494 non-null  int64 
 2   year    871494 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 19.9+ MB


In [22]:
df_names.describe()

amount           year
count  871494.000000  871494.000000
mean        4.278225    2012.267647
std        34.615712       1.370919
min         1.000000    2010.000000
25%         1.000000    2011.000000
50%         1.000000    2012.000000
75%         2.000000    2013.000000
max      4960.000000    2014.000000

## Some Pandas useful functions

**TODO:** Investigate the functions that are implemented in the next cell. What do they do? What do you think they can be useful for?

In [24]:
# df_names.head()
# df_names.tail()
# df_names.count()
df_names.shape

(871494, 3)

## Append a new row

**TODO:** Suppose that in the data load, someone forgot to add a name and its respective amount and year.

Let's add to our dataset the following row with said information:

Name: "Daenerys Stormborn of the House Targaryen, First of Her Name de ella, the Unburnt, Queen of the Andals and the First Men, Khaleesi of the Great Grass Sea, Breaker of Chains, and Mother of Dragons"

Amount: 100
Year: 2011

In [25]:
new_name = {'name': 'Fefo',
    'amount': 100,
    'year': 2011}

df_names = df_names.append(new_name, ignore_index=True)
df_names

name  amount  year
0                     Benjamin    2986  2010
1                        Sofia    2252  2010
2                     Bautista    2176  2010
3                      Joaquín    2111  2010
4                 Juan Ignacio    2039  2010
...                        ...     ...   ...
871490  Isaias Sebastian Ariel       1  2014
871491        Yanira Valentina       1  2014
871492            Angie Ainara       1  2014
871493          Elias Hernando       1  2014
871494                    Fefo     100  2011

[871495 rows x 3 columns]

**TODO:** Investigate the columns and index functions. What do they do? What data type is their output? What known data type do they resemble?

In [30]:
# df_names.columns
# df_names.index


RangeIndex(start=0, stop=871495, step=1)

**TODO:** What do the following operations do

In [51]:
df_names['amount']
# df_names[['year', 'name']]
# df_names.year
# 'name' in df_names

0         2986
1         2252
2         2176
3         2111
4         2039
          ... 
871490       1
871491       1
871492       1
871493       1
871494     100
Name: amount, Length: 871495, dtype: int64

**TODO:** Add a column to the dataframe that corresponds to the number of characters in each name

## Add a new column

In [49]:
df_names['amount_char'] = df_names['name'].str.len()
df_names

name  amount  year  amount_chars  amount_char
0                     Benjamin    2986  2010             8            8
1                        Sofia    2252  2010             5            5
2                     Bautista    2176  2010             8            8
3                      Joaquín    2111  2010             7            7
4                 Juan Ignacio    2039  2010            12           12
...                        ...     ...   ...           ...          ...
871490  Isaias Sebastian Ariel       1  2014            22           22
871491        Yanira Valentina       1  2014            16           16
871492            Angie Ainara       1  2014            12           12
871493          Elias Hernando       1  2014            14           14
871494                    Fefo     100  2011             4            4

[871495 rows x 5 columns]

## Filtering by mask

Its implementation is very similar in both NumPy and Pandas, so we will see how to do it first in NumPy then in Pandas.

Suppose we make 100 rolls of a dice, but we want to select only those rolls that were less than four. How can we do it?

In [52]:
dice = np.random.randint(1, 7, size=100)
print(dice)

[1 3 1 6 1 3 5 2 2 2 3 4 5 2 6 3 3 5 2 1 3 1 5 2 4 1 5 3 6 3 1 2 1 5 5 6 1
 3 4 4 1 6 6 2 1 3 1 2 4 3 4 3 1 3 3 4 1 5 1 5 1 3 6 5 3 2 2 1 6 6 5 6 5 2
 5 2 6 5 1 1 3 4 4 4 3 4 2 5 3 6 4 2 2 2 5 2 6 5 3 1]


What we can do is create a mask:

In [59]:
a = dice > 3
print(a)
print(type(a))

[False False False  True False False  True False False False False  True
  True False  True False False  True False False False False  True False
  True False  True False  True False False False False  True  True  True
 False False  True  True False  True  True False False False False False
  True False  True False False False False  True False  True False  True
 False False  True  True False False False False  True  True  True  True
  True False  True False  True  True False False False  True  True  True
 False  True False  True False  True  True False False False  True False
  True  True False False]
<class 'numpy.ndarray'>


In [64]:
print(dice[a])

[5 3 1 3 5 3 3 1 3 5 3 3 5 1 1 5 5 1 1 1 3 3 5 3 5 5 3 5 3 3 5 3 1 1 1 1 3
 5 1 3 5 3]


In [65]:
print(dice.sum())

327


In [66]:
print(dice[dice > 3])

[6 5 4 5 6 5 5 4 5 6 5 5 6 4 4 6 6 4 4 4 5 5 6 5 6 6 5 6 5 5 6 5 4 4 4 4 5
 6 4 5 6 5]


**TODO:** Going back to our dataset, suppose we want to keep those names that were repeated more than 2000 times

In [71]:
mu = df_names['amount'] > 2000
print(df_names[mu])
print(mu)
new_df['amount'].unique()

0          True
1          True
2          True
3          True
4          True
          ...  
871490    False
871491    False
871492    False
871493    False
871494    False
Name: amount, Length: 871495, dtype: bool


**TODO:** What if we want to select those names with more than 8 letters and from 2010 onwards?

In [ ]:
# To complete

## Statistics

**TODO:** Obtain the mean value and standard deviation of each numeric column. Is there a function in Pandas that will give us even more statistics?

In [ ]:
# To complete

## Delete a column

**TODO:** Throw the column amount_chars.

In [ ]:
# To complete

## Sorting by column

**TODO:** Sort the dataframe by amount and descending

In [ ]:
# To complete

## Pandas groupby and plot

**TODO:** Group the number of names by year and plot it using vertical bars

In [ ]:
# To complete